UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 60
	WHERE CANTIDADCREDITOS = 30
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 56
	WHERE CANTIDADCREDITOS = 28
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';

UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 52
	WHERE CANTIDADCREDITOS = 26
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';

UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 48
	WHERE CANTIDADCREDITOS = 24
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';			
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 42
	WHERE CANTIDADCREDITOS = 21
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';				
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 36
	WHERE CANTIDADCREDITOS = 18
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';				

UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 28
	WHERE CANTIDADCREDITOS = 14
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';				
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 20
	WHERE CANTIDADCREDITOS = 10
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';				
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 12
	WHERE CANTIDADCREDITOS = 6
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 6
	WHERE CANTIDADCREDITOS = 3
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';								
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 4
	WHERE CANTIDADCREDITOS = 2
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';
	
UPDATE MOVIMIENTOCREDITOS
	SET CANTIDADCREDITOS = 2
	WHERE CANTIDADCREDITOS = 1
	AND TIPOMOVIMIENTOCREDITOS = 'CargaInicialAgenteExistente';																																					